---
# tasks file for java_finder

- name: Include checks/asserts
  import_tasks: asserts.yml

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

#############################################################################
# Tasks for all *NIX operating systems
#############################################################################
- block:

    - name: "Set JAVAP"
      shell: java -version
      register: JAVAP

    - name: "debug"
      debug: msg={{JAVAP.stderr_lines}}

#    - name: "Create custom fact directory"
#      file:
#        path: "/etc/ansible/facts.d"
#        state: "directory"

#    - name: "Insert custom fact file"
#      copy:
#        src: files/custom.fact
#        dest: /etc/ansible/facts.d/custom.fact
#        mode: 0755

#    - name: "Re-run setup to use custom facts"
#      setup: filter=ansible_local

  when: ansible_os_family != 'Windows'

#############################################################################
# End of tasks for all *NIX operating systems
#############################################################################

#############################################################################
# Tasks for Windows
#############################################################################

- block:
    
    - name: Test the PsExec connection to the local system (target node) with your user
      win_shell: Get-WmiObject -Class Win32_Product -ComputerName {{ ansible_hostname }} -Filter "Name like 'Java%'" | Select Name, Version
      register: winshell

    - name: "debug windows"
      debug: msg={{winshell.stdout_lines}}

  when: ansible_os_family == 'Windows'
  
