---
# tasks file for java_finder

- name: Include checks/asserts
  import_tasks: asserts.yml

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

#############################################################################
# Tasks for all *NIX operating systems
#############################################################################
- block:

    - name: "Create custom fact directory"
      file:
        path: "/etc/ansible/facts.d"
        state: "directory"

    - name: "Insert custom fact file"
      copy:
        src: files/custom.fact
        dest: /etc/ansible/facts.d/custom.fact
        mode: 0755

    - name: "Re-run setup to use custom facts"
      setup: filter=ansible_local

  when: ansible_os_family != 'Windows'

#############################################################################
# End of tasks for all *NIX operating systems
#############################################################################

#############################################################################
# Tasks for Windows
#############################################################################

#- block:






#  when: ansible_os_family == 'Windows'
  
