---
# tasks file for java_finder

- name: Include checks/asserts
  import_tasks: asserts.yml

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

#############################################################################
# Tasks for all *NIX operating systems
#############################################################################
- block:

    - name: Check for Java Version if in PATH
      shell: java -version 2>&1 | grep version
      register: java_version
      ignore_errors: yes

    - name: Check for Java processes
      shell: ps -ef | grep java -A 1 | grep -v grep
      register: java_process
      ignore_errors: yes

    - debug: var=java_version

    - debug: var=java_process

  when: ansible_os_family != 'Windows'

#############################################################################
# End of tasks for all *NIX operating systems
#############################################################################

#############################################################################
# Tasks for Windows
#############################################################################

#- block:






#  when: ansible_os_family == 'Windows'
  